// Auto-generated by Xcode Build Phase. Do not edit.
// Values below are placeholders overwritten at build time with git info.

enum BuildInfo {
    nonisolated static let gitCommitHash = "unknown"
    nonisolated static let gitCommitHashFull = "unknown"
    nonisolated static let version = "1.0"
}
