name: Test

on:
  workflow_call:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  unit-test:
    name: Unit Tests
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run unit tests
        run: |
          xcodebuild -project Cmod.xcodeproj \
            -scheme Cmod \
            -destination 'platform=macOS' \
            -only-testing:CmodTests \
            test
